### ISSUE TITLE
PayFort android

### ISSUE THREAD

**Issue by JackTimber** [payfort/start-android-sdk#3]
Remember me option is not working and
when enter expiry date and entered **.**, application crashed

**Comment by alovak** [comment]
@JackTimber I can't find 'remember me' function in our SDK. Can you please tell me where it is located?

**Comment by JackTimber** [comment]
crashed on when press .
FATAL EXCEPTION: main
                                                           Process: com.fixit, PID: 10425
                                                           java.lang.NumberFormatException: Invalid int: "."
                                                               at java.lang.Integer.invalidInt(Integer.java:138)
                                                               at java.lang.Integer.parse(Integer.java:410)
                                                               at java.lang.Integer.parseInt(Integer.java:367)
                                                               at java.lang.Integer.parseInt(Integer.java:334)
                                                               at com.payfort.fort.android.sdk.service.impl.CreditPaymentServiceImpl.formatExpiryDate(CreditPaymentServiceImpl.java:143)
                                                               at com.payfort.fort.android.sdk.activities.CreditCardPaymentActivity$7.afterTextChanged(CreditCardPaymentActivity.java:307)
                                                               at android.widget.TextView.sendAfterTextChanged(TextView.java:8009)
                                                               at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10170)
                                                               at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
                                                               at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
                                                               at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
                                                               at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:184)
                                                               at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
                                                               at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JackTimber** [comment]
dot(.) and remember me option

![payfort3](https://user-images.githubusercontent.com/32217488/30796418-8c32356e-a1ef-11e7-944b-b43460774197.png)

**Comment by alovak** [comment]
@JackTimber this repository is for Start Android SDK. As far as I see from backtrace and from UI you are using FORT SDK. Please, send all your requests at integration@payfort.com. I will send them email as well with links to this issues.
